### ISSUE TITLE
The tables on the right side of the UI do not display any data

### ISSUE THREAD

**Issue by Neithar** [Yezree/AplikacjaBMI#7]
I suppose that these are meant to store previous BMI inputs, but nothing is displayed at all in them.

**Comment by Yezree** [comment]
Zrobię to, ale mamy problem, podczas uruchomienia wyskakuje poniższy błąd. 
![image](https://user-images.githubusercontent.com/74781098/215148155-0263052b-5438-4704-bf47-aa45c9070702.png)

**Comment by Yezree** [comment]
Dobra, problem się rozwiązał po zainstalowaniu środowiska uruchomieniowego programu Microsoft Access 2016.
![Aplikacja](https://user-images.githubusercontent.com/74781098/215148613-e11b073f-1731-490b-92eb-dc5d2213484b.png)
